// Full dataset of 44 IPA sounds with exact classifications, guidelines, local audio paths & online backup URLs
const ipaData = [
    // Short Vowels (7)
    { id: 1, ipa: "/ɪ/", type1: "Nguyên âm", type2: "Nguyên âm ngắn", guide: "Âm i ngắn, phát âm giống 'i' tiếng Việt nhưng ngắn hơn, bật nhanh. Môi hơi mở sang hai bên, lưỡi hạ thấp.", examples: "his /hɪz/, kid /kɪd/", audioQuery: "his kid", audioUrl: "audio/i_ngan.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/i%20ng%E1%BA%AFn.mp3" },
    { id: 2, ipa: "/e/", type1: "Nguyên âm", type2: "Nguyên âm ngắn", guide: "Tương tự âm 'e' tiếng Việt nhưng phát âm ngắn hơn. Môi mở rộng sang hai bên rộng hơn âm /ɪ/, lưỡi hạ thấp hơn /ɪ/.", examples: "bed /bed/, head /hed/", audioQuery: "bed head", audioUrl: "audio/e.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/e.mp3" },
    { id: 3, ipa: "/æ/", type1: "Nguyên âm", type2: "Nguyên âm ngắn", guide: "Âm a bẹt, lai giữa âm 'a' và 'e', âm nén xuống. Miệng mở rộng, môi dưới hạ thấp xuống, lưỡi hạ rất thấp.", examples: "trap /træp/, bad /bæd/", audioQuery: "trap bad", audioUrl: "audio/ae.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/ae.mp3" },
    { id: 4, ipa: "/ɒ/", type1: "Nguyên âm", type2: "Nguyên âm ngắn", guide: "Âm o ngắn, tương tự âm 'o' tiếng Việt nhưng phát âm ngắn hơn. Môi hơi tròn, lưỡi hạ thấp.", examples: "hot /hɒt/, box /bɒks/", audioQuery: "hot box", audioUrl: "audio/o_ngan.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/o%20ng%E1%BA%AFn.mp3" },
    { id: 5, ipa: "/ʊ/", type1: "Nguyên âm", type2: "Nguyên âm ngắn", guide: "Âm u ngắn, khá giống âm 'ư' tiếng Việt. Không dùng môi mà đẩy hơi rất ngắn từ cổ họng. Môi hơi tròn, lưỡi hạ thấp.", examples: "good /ɡʊd/, put /pʊt/", audioQuery: "good put", audioUrl: "audio/u_ngan.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/u%20ng%E1%BA%AFn.mp3" },
    { id: 6, ipa: "/ʌ/", type1: "Nguyên âm", type2: "Nguyên âm ngắn", guide: "Âm lai giữa âm 'ă' và âm 'ơ' tiếng Việt (thiên về 'ă' hơn). Phát âm bật hơi ra. Miệng thu hẹp lại, lưỡi hơi nâng lên cao.", examples: "come /kʌm/, love /lʌv/", audioQuery: "come love", audioUrl: "audio/a_ngan.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/a%20ng%E1%BA%AFn.mp3" },
    { id: 7, ipa: "/ə/", type1: "Nguyên âm", type2: "Nguyên âm ngắn", guide: "Âm ơ ngắn (Schwa), phát âm như âm 'ơ' tiếng Việt nhưng ngắn và nhẹ hơn. Môi hơi mở rộng, lưỡi thả lỏng.", examples: "banana /bəˈnɑːnə/, doctor /ˈdɒktə(r)/", audioQuery: "banana doctor", audioUrl: "audio/ơ_ngan.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/%C6%A1%20ng%E1%BA%AFn.mp3" },

    // Long Vowels (5)
    { id: 8, ipa: "/iː/", type1: "Nguyên âm", type2: "Nguyên âm dài", guide: "Âm i dài, kéo dài âm 'i', âm phát từ trong khoang miệng chứ không thổi hơi ra. Môi mở rộng hai bên như đang mỉm cười, lưỡi nâng cao lên.", examples: "sea /siː/, green /ɡriːn/", audioQuery: "sea green", audioUrl: "audio/i_dai.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/i%20d%C3%A0i.mp3" },
    { id: 9, ipa: "/ɑː/", type1: "Nguyên âm", type2: "Nguyên âm dài", guide: "Âm 'a' đọc kéo dài, âm phát ra từ khoang miệng. Môi mở rộng, lưỡi hạ thấp.", examples: "start /stɑːt/, father /ˈfɑːðə(r)/", audioQuery: "start father", audioUrl: "audio/a_dai.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/a%20d%C3%A0i.mp3" },
    { id: 10, ipa: "/ɔː/", type1: "Nguyên âm", type2: "Nguyên âm dài", guide: "Phát âm như âm 'o' tiếng Việt nhưng rồi cong lưỡi lên, không phát âm từ khoang miệng. Tròn môi, lưỡi cong lên chạm vòm miệng khi kết thúc.", examples: "ball /bɔːl/, law /lɔː/", audioQuery: "ball law", audioUrl: "audio/o_dai.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/o%20d%C3%A0i.mp3" },
    { id: 11, ipa: "/uː/", type1: "Nguyên âm", type2: "Nguyên âm dài", guide: "Âm u dài, âm phát ra từ khoang miệng nhưng không thổi hơi ra, kéo dài âm u ngắn. Môi tròn, lưỡi nâng cao lên.", examples: "goose /ɡuːs/, school /skuːl/", audioQuery: "goose school", audioUrl: "audio/u_dai.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/u%20d%C3%A0i.mp3" },
    { id: 12, ipa: "/ɜː/", type1: "Nguyên âm", type2: "Nguyên âm dài", guide: "Âm ơ dài cong lưỡi. Phát âm /ə/ rồi cong lưỡi lên, âm phát từ trong khoang miệng. Môi hơi mở rộng, lưỡi chạm vòm miệng khi kết thúc.", examples: "burn /bɜːn/, birthday /ˈbɜːθdeɪ/", audioQuery: "burn birthday", audioUrl: "audio/ơ_dai.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/%C6%A1%20d%C3%A0i.mp3" },

    // Diphthongs (8)
    { id: 13, ipa: "/ɪə/", type1: "Nguyên âm", type2: "Nguyên âm đôi", guide: "Nguyên âm đôi chuyển từ âm /ɪ/ rồi dần sang âm /ə/. Môi mở rộng dần nhưng không rộng quá. Lưỡi đẩy dần ra về phía trước.", examples: "near /nɪə(r)/, here /hɪə(r)/", audioQuery: "near here", audioUrl: "audio/ie.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/ie.mp3" },
    { id: 14, ipa: "/eə/", type1: "Nguyên âm", type2: "Nguyên âm đôi", guide: "Phát âm bằng cách đọc âm /e/ rồi chuyển dần sang âm /ə/. Môi hơi thu hẹp. Lưỡi thụt dần về phía sau.", examples: "hair /heə(r)/, there /ðeə(r)/", audioQuery: "hair there", audioUrl: "audio/ea.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/ea.mp3" },
    { id: 15, ipa: "/eɪ/", type1: "Nguyên âm", type2: "Nguyên âm đôi", guide: "Phát âm bằng cách đọc âm /e/ rồi chuyển dần sang âm /ɪ/. Môi dẹt dần sang hai bên. Lưỡi hướng dần lên trên.", examples: "face /feɪs/, day /deɪ/", audioQuery: "face day", audioUrl: "audio/ei.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/ei.mp3" },
    { id: 16, ipa: "/ɔɪ/", type1: "Nguyên âm", type2: "Nguyên âm đôi", guide: "Phát âm bằng cách đọc âm /ɔː/ rồi chuyển dần sang âm /ɪ/. Môi dẹt dần sang hai bên. Lưỡi nâng lên và đẩy dần về phía trước.", examples: "choice /tʃɔɪs/, boy /bɔɪ/", audioQuery: "choice boy", audioUrl: "audio/oi.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/oi.mp3" },
    { id: 17, ipa: "/aɪ/", type1: "Nguyên âm", type2: "Nguyên âm đôi", guide: "Phát âm bằng cách đọc âm /ɑː/ rồi chuyển dần sang âm /ɪ/. Môi dẹt dần sang hai bên. Lưỡi nâng lên và hơi đẩy dần về trước.", examples: "nice /naɪs/, try /traɪ/", audioQuery: "nice try", audioUrl: "audio/ai.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/a%C9%AA.mp3" },
    { id: 18, ipa: "/əʊ/", type1: "Nguyên âm", type2: "Nguyên âm đôi", guide: "Phát âm bằng cách đọc âm /ə/ rồi chuyển dần sang âm /ʊ/. Môi từ hơi mở đến hơi tròn. Lưỡi lùi dần về phía sau.", examples: "goat /ɡəʊt/, show /ʃəʊ/", audioQuery: "goat show", audioUrl: "audio/ou.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/%C9%99%CA%8A.mp3" },
    { id: 19, ipa: "/aʊ/", type1: "Nguyên âm", type2: "Nguyên âm đôi", guide: "Phát âm bằng cách đọc âm /ɑː/ rồi chuyển dần sang âm /ʊ/. Môi tròn dần. Lưỡi hơi thụt về phía sau.", examples: "mouth /maʊθ/, cow /kaʊ/", audioQuery: "mouth cow", audioUrl: "audio/au.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/a%CA%8A.mp3" },
    { id: 20, ipa: "/ʊə/", type1: "Nguyên âm", type2: "Nguyên âm đôi", guide: "Chuyển từ âm /ʊ/ sang âm /ə/. Bắt đầu môi mở khá tròn, hơi bè, mặt lưỡi hướng lên ngạc trên. Sau đó miệng hơi mở, đưa lưỡi lùi về giữa.", examples: "sure /ʃʊə(r)/, tour /tʊə(r)/", audioQuery: "sure tour", audioUrl: "audio/ua.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/%CA%8A%C9%99.mp3" },

    // Unvoiced Consonants (9)
    { id: 21, ipa: "/p/", type1: "Phụ âm", type2: "Phụ âm vô thanh", guide: "Đọc gần giống âm P tiếng Việt, hai môi chặn luồng không khí trong miệng sau đó bật ra. Không rung dây thanh quản.", examples: "pen /pen/, copy /ˈkɒpi/", audioQuery: "pen copy", audioUrl: "audio/p.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/p.mp3" },
    { id: 22, ipa: "/t/", type1: "Phụ âm", type2: "Phụ âm vô thanh", guide: "Giống âm T tiếng Việt nhưng bật hơi mạnh hơn. Đặt đầu lưỡi dưới nướu, khi bật luồng khí ra lưỡi chạm răng cửa dưới. Không rung thanh quản.", examples: "tea /tiː/, tight /taɪt/", audioQuery: "tea tight", audioUrl: "audio/t.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/t.mp3" },
    { id: 23, ipa: "/k/", type1: "Phụ âm", type2: "Phụ âm vô thanh", guide: "Giống âm K tiếng Việt nhưng bật hơi mạnh bằng cách nâng phần sau lưỡi chạm ngạc mềm, hạ thấp khi khí bật ra. Không rung dây thanh.", examples: "key /kiː/, school /skuːl/", audioQuery: "key school", audioUrl: "audio/k.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/k.mp3" },
    { id: 24, ipa: "/f/", type1: "Phụ âm", type2: "Phụ âm vô thanh", guide: "Tương tự âm PH tiếng Việt. Khi phát âm, hàm trên chạm nhẹ vào môi dưới, đẩy không khí thoát ra ngoài.", examples: "fat /fæt/, coffee /ˈkɒfi/", audioQuery: "fat coffee", audioUrl: "audio/f.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/f.mp3" },
    { id: 25, ipa: "/θ/", type1: "Phụ âm", type2: "Phụ âm vô thanh", guide: "Đặt đầu lưỡi ở giữa hai hàm răng, để luồng khí thoát ra giữa lưỡi và 2 hàm răng. Thanh quản không rung.", examples: "thin /θɪn/, path /pɑːθ/", audioQuery: "thin path", audioUrl: "audio/theta.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/%CE%B8.mp3" },
    { id: 26, ipa: "/s/", type1: "Phụ âm", type2: "Phụ âm vô thanh", guide: "Lưỡi đặt nhẹ lên hàm trên, ngạc mềm nâng, luồng khí thoát từ giữa mặt lưỡi và lợi. Không rung thanh quản.", examples: "soon /suːn/, sister /ˈsɪstə(r)/", audioQuery: "soon sister", audioUrl: "audio/s.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/s.mp3" },
    { id: 27, ipa: "/ʃ/", type1: "Phụ âm", type2: "Phụ âm vô thanh", guide: "Môi chu ra hướng về phía trước, tròn môi. Mặt lưỡi chạm lợi hàm trên và nâng phần phía trước của lưỡi lên.", examples: "ship /ʃɪp/, sure /ʃɔː(r)/", audioQuery: "ship sure", audioUrl: "audio/sh.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/%E2%88%AB.mp3" },
    { id: 28, ipa: "/tʃ/", type1: "Phụ âm", type2: "Phụ âm vô thanh", guide: "Tương tự âm CH. Môi hơi tròn chu ra trước. Khí thoát ra thì lưỡi thẳng chạm hàm dưới, không rung thanh quản.", examples: "church /tʃɜːtʃ/, match /mætʃ/", audioQuery: "church match", audioUrl: "audio/ch.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/t%E2%88%AB.mp3" },
    { id: 29, ipa: "/h/", type1: "Phụ âm", type2: "Phụ âm vô thanh", guide: "Đọc như âm H tiếng Việt, môi hé nửa, lưỡi hạ thấp để khí thoát ra tự do. Thanh quản không rung.", examples: "hot /hɒt/, behind /bɪˈhaɪnd/", audioQuery: "hot behind", audioUrl: "audio/h.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/h.mp3" },

    // Voiced Consonants (15)
    { id: 30, ipa: "/b/", type1: "Phụ âm", type2: "Phụ âm hữu thanh", guide: "Đọc tương tự âm B tiếng Việt. Hai môi chặn không khí từ trong miệng sau đó bật ra. Thanh quản rung nhẹ.", examples: "back /bæk/, job /dʒɒb/", audioQuery: "back job", audioUrl: "audio/b.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/b.mp3" },
    { id: 31, ipa: "/d/", type1: "Phụ âm", type2: "Phụ âm hữu thanh", guide: "Giống âm D tiếng Việt, bật hơi mạnh. Đặt đầu lưỡi dưới nướu, khi khí bật ra đầu lưỡi chạm răng cửa dưới. Thanh quản rung.", examples: "day /deɪ/, ladder /ˈlædə(r)/", audioQuery: "day ladder", audioUrl: "audio/d.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/d.mp3" },
    { id: 32, ipa: "/g/", type1: "Phụ âm", type2: "Phụ âm hữu thanh", guide: "Giống âm G tiếng Việt. Nâng phần sau của lưỡi chạm ngạc mềm, hạ thấp khi luồng khí bật ra sao cho rung dây thanh.", examples: "get /ɡet/, ghost /ɡəʊst/", audioQuery: "get ghost", audioUrl: "audio/g.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/g.mp3" },
    { id: 33, ipa: "/v/", type1: "Phụ âm", type2: "Phụ âm hữu thanh", guide: "Đọc như âm V tiếng Việt. Khi phát âm, hàm trên chạm nhẹ vào môi dưới, đẩy hơi làm rung thanh quản.", examples: "view /vjuː/, move /muːv/", audioQuery: "view move", audioUrl: "audio/v.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/v.mp3" },
    { id: 34, ipa: "/ð/", type1: "Phụ âm", type2: "Phụ âm hữu thanh", guide: "Đặt đầu lưỡi ở giữa hai hàm răng, để luồng khí thoát ra giữa lưỡi và 2 hàm răng. Thanh quản rung.", examples: "this /ðɪs/, other /ˈʌðə(r)/", audioQuery: "this other", audioUrl: "audio/eth.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/%C3%B0.mp3" },
    { id: 35, ipa: "/z/", type1: "Phụ âm", type2: "Phụ âm hữu thanh", guide: "Lưỡi đặt nhẹ lên hàm trên, ngạc mềm nâng, luồng khí thoát từ giữa mặt lưỡi và lợi làm rung thanh quản.", examples: "zero /ˈzɪərəʊ/, buzz /bʌz/", audioQuery: "zero buzz", audioUrl: "audio/z.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/z.mp3" },
    { id: 36, ipa: "/ʒ/", type1: "Phụ âm", type2: "Phụ âm hữu thanh", guide: "Môi chu ra hướng về phía trước, tròn môi. Mặt lưỡi chạm lợi hàm trên, nâng phần trước lưỡi và rung thanh quản.", examples: "pleasure /ˈpleʒə(r)/, vision /ˈvɪʒn/", audioQuery: "pleasure vision", audioUrl: "audio/zh.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/%CA%92.mp3" },
    { id: 37, ipa: "/dʒ/", type1: "Phụ âm", type2: "Phụ âm hữu thanh", guide: "Phát âm giống /tʃ/ nhưng có rung dây thanh quản. Môi hơi tròn chu về trước, lưỡi chạm hàm dưới.", examples: "age /eɪdʒ/, gym /dʒɪm/", audioQuery: "age gym", audioUrl: "audio/dzh.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/d%CA%92.mp3" },
    { id: 38, ipa: "/m/", type1: "Phụ âm", type2: "Phụ âm hữu thanh", guide: "Âm mũi, đọc giống âm M tiếng Việt, hai môi ngậm lại, luồng khí thoát ra hoàn toàn bằng mũi.", examples: "money /ˈmʌn.i/, mean /miːn/", audioQuery: "money mean", audioUrl: "audio/m.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/m.mp3" },
    { id: 39, ipa: "/n/", type1: "Phụ âm", type2: "Phụ âm hữu thanh", guide: "Âm mũi, đọc như âm N tiếng Việt. Môi hé, đầu lưỡi chạm lợi hàm trên, chặn khí phát ra từ mũi.", examples: "nice /naɪs/, sun /sʌn/", audioQuery: "nice sun", audioUrl: "audio/n.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/n.mp3" },
    { id: 40, ipa: "/ŋ/", type1: "Phụ âm", type2: "Phụ âm hữu thanh", guide: "Âm mũi, chặn khí ở lưỡi, môi hé, phần sau của lưỡi nâng lên chạm ngạc mềm, khí phát qua mũi, thanh quản rung.", examples: "ring /rɪŋ/, long /lɒŋ/", audioQuery: "ring long", audioUrl: "audio/ng.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/%CE%B7.mp3" },
    { id: 41, ipa: "/l/", type1: "Phụ âm", type2: "Phụ âm hữu thanh", guide: "Cong lưỡi từ từ chạm răng hàm trên, thanh quản rung, môi mở rộng hoàn toàn, đầu lưỡi cong đặt vào môi hàm trên.", examples: "light /laɪt/, feel /fiːl/", audioQuery: "light feel", audioUrl: "audio/l.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/l.mp3" },
    { id: 42, ipa: "/r/", type1: "Phụ âm", type2: "Phụ âm hữu thanh", guide: "Khác âm R tiếng Việt. Cong lưỡi vào trong, môi tròn hơi chu ra. Khi khí thoát ra thì lưỡi thả lỏng, môi mở rộng.", examples: "right /raɪt/, sorry /ˈsɒri/", audioQuery: "right sorry", audioUrl: "audio/r.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/r.mp3" },
    { id: 43, ipa: "/w/", type1: "Phụ âm", type2: "Phụ âm hữu thanh", guide: "Môi tròn, chu về phía trước, lưỡi thả lỏng. Khi luồng khí phát ra thì môi mở rộng, lưỡi vẫn thả lỏng.", examples: "wet /wet/, win /wɪn/", audioQuery: "wet win", audioUrl: "audio/w.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/w.mp3" },
    { id: 44, ipa: "/j/", type1: "Phụ âm", type2: "Phụ âm hữu thanh", guide: "Nâng phần trước lưỡi gần ngạc cứng, đẩy khí thoát ra làm rung dây thanh quản. Môi hơi mở rộng khi khí phát ra.", examples: "yes /jes/, use /juːz/", audioQuery: "yes use", audioUrl: "audio/j.mp3", remoteAudioUrl: "https://st.ielts-fighter.com/src/ielts-fighter/2019/09/09/j.mp3" }
];
